// @ts-nocheck
"use client";

const SERIF = "'Fraunces', 'Georgia', serif";

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#faf8f4", fontFamily: "'Inter', system-ui, sans-serif", color: "#1a1613" }}>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px" }}>

        <div style={{ marginBottom: 40 }}>
          <div style={{ fontFamily: SERIF, fontSize: 32, fontWeight: 600, marginBottom: 8 }}>Terms of Service</div>
          <div style={{ fontSize: 13, color: "#9ca3af" }}>Texas Events Trust Fund Analysis Tool · Last updated April 2026</div>
        </div>

        {[
          {
            title: "1. About This Tool",
            body: `The Texas Events Trust Fund Analysis Tool ("the Tool") is an independent planning resource designed to help Destination Marketing Organizations (DMOs), Convention & Visitor Bureaus (CVBs), and local organizing committees evaluate, analyze, and prepare applications for the Texas Events Trust Fund program administered by the Office of the Governor's Economic Development and Tourism division (EDT).

This Tool is NOT affiliated with, endorsed by, or operated by the State of Texas, the Office of the Governor, or EDT. It does not constitute an official application submission, guarantee of funding, or legal advice of any kind.`
          },
          {
            title: "2. No Guarantee of Funding",
            body: `Use of this Tool does not guarantee approval of any Events Trust Fund application. All ETF determinations are made solely by EDT based on the official program guidelines, applicable statutes (Texas Government Code Chapter 480), and Texas Administrative Code. The projections, estimates, and analyses generated by this Tool are for internal planning purposes only and may not reflect actual ETF award amounts.`
          },
          {
            title: "3. Accuracy of Information",
            body: `You are solely responsible for the accuracy, completeness, and truthfulness of all data entered into this Tool. Knowingly submitting false information in official ETF applications may constitute a felony offense under Texas Penal Code § 37.10. This Tool does not verify the accuracy of data entered by users.`
          },
          {
            title: "4. Data Ownership",
            body: `You and your organization retain ownership of all event data, analyses, and content you enter into the Tool. By using the Tool, you grant us a limited license to store and process your data solely for the purpose of providing the Tool's functionality. We do not claim ownership of your data and will not sell, license, or share your proprietary event data with third parties.`
          },
          {
            title: "5. Acceptable Use",
            body: `You agree to use this Tool only for lawful purposes related to ETF program planning and administration. You agree not to: (a) share your access code with unauthorized parties outside your organization; (b) enter false or misleading information; (c) attempt to access other organizations' data; (d) reverse engineer or copy the Tool for commercial redistribution without permission.`
          },
          {
            title: "6. Limitation of Liability",
            body: `This Tool is provided "as is" without warranty of any kind. We are not liable for any errors in ETF analyses or projections, missed application deadlines, denied ETF applications, data loss due to technical failures, or any indirect, incidental, or consequential damages arising from use of the Tool. Your use of this Tool is entirely at your own risk.`
          },
          {
            title: "7. Access and Termination",
            body: `We reserve the right to suspend or terminate access to the Tool at any time, for any reason, including misuse or violation of these Terms. We will make reasonable efforts to provide notice of significant changes or discontinuation.`
          },
          {
            title: "8. Changes to Terms",
            body: `We may update these Terms from time to time. Continued use of the Tool after changes are posted constitutes acceptance of the updated Terms. We will update the "Last updated" date at the top of this page when changes are made.`
          },
          {
            title: "9. Contact",
            body: `Questions about these Terms can be directed to the tool administrator. For questions about the ETF program itself, contact EDT directly at eventsfund@gov.texas.gov.`
          },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: 32 }}>
            <div style={{ fontFamily: SERIF, fontSize: 18, fontWeight: 600, marginBottom: 10 }}>{section.title}</div>
            <div style={{ fontSize: 14, lineHeight: 1.8, color: "#374151", whiteSpace: "pre-line" }}>{section.body}</div>
          </div>
        ))}

        <div style={{ marginTop: 48, paddingTop: 24, borderTop: "1px solid #e8e3db", display: "flex", gap: 20 }}>
          <a href="/privacy" style={{ fontSize: 13, color: "#6b6660" }}>Privacy Policy</a>
          <a href="/" style={{ fontSize: 13, color: "#6b6660" }}>Back to Tool</a>
        </div>
      </div>
    </div>
  );
}
